[tool.poetry]
name = "spread-wings-bot"
version = "0.1.0"
description = "add later"
authors = ["add later"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.1"
python-telegram-bot = "^20.3"
pydantic = "^1.10.7"
pytest = "^7.3.1"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
isort = "^5.12.0"
pre-commit = "^3.3.1"
python-dotenv = "^1.0.0"
black = "^23.3.0"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
