# Generated by Django 4.2.3 on 2023-07-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(max_length=3856),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(max_length=200),
        ),
    ]
