# Generated by Django 4.2.4 on 2023-08-23 18:19

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    """New field in FundProgram."""

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundprogram",
            name="fund_text",
            field=mdeditor.fields.MDTextField(
                max_length=4096, verbose_name="Описание программы"
            ),
        ),
    ]
