# Generated by Django 4.2.4 on 2023-08-25 17:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    """Migrations for FundProgram."""

    dependencies = [
        ("bot", "0002_alter_coordinator_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundprogram",
            name="fund_text",
            field=ckeditor.fields.RichTextField(
                max_length=4096, verbose_name="Описание программы"
            ),
        ),
    ]
