# Generated by Django 4.2.4 on 2023-08-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa
    dependencies = [
        ("bot", "0002_alter_coordinator_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coordinator",
            options={
                "ordering": ("is_chief", "last_name"),
                "verbose_name": "Координатор",
                "verbose_name_plural": "Координаторы",
            },
        ),
        migrations.AddField(
            model_name="coordinator",
            name="is_chief",
            field=models.BooleanField(default=False),
        ),
    ]
