# Generated by Django 4.2.4 on 2023-08-29 18:57

from django.db import migrations, models

import bot.validators


class Migration(migrations.Migration):
    """Migrations for bot."""

    dependencies = [
        ("bot", "0003_alter_coordinator_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coordinator",
            options={
                "ordering": ("-is_chief", "last_name"),
                "verbose_name": "Координатор",
                "verbose_name_plural": "Координаторы",
            },
        ),
        migrations.AddField(
            model_name="coordinator",
            name="is_chief",
            field=models.BooleanField(
                default=False,
                validators=[bot.validators.validate_is_chief],
                verbose_name="Главный",
            ),
        ),
    ]
