# Generated by Django 4.2.4 on 2023-08-31 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations for bot."""

    dependencies = [
        ("core", "0002_alter_region_region_name"),
        ("bot", "0004_alter_coordinator_options_coordinator_is_chief"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="email_address",
            field=models.EmailField(
                help_text="Введите адрес электронной почты",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="region",
            field=models.OneToOneField(
                help_text="Выберите регион из списка",
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name="coordinators",
                serialize=False,
                to="core.region",
                verbose_name="Регион",
            ),
        ),
        migrations.AlterField(
            model_name="fundprogram",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите регион(ы) для программы",
                related_name="programs",
                to="core.region",
                verbose_name="Регионы",
            ),
        ),
    ]
