# Generated by Django 4.2.4 on 2023-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations for bot."""

    dependencies = [
        ("bot", "0004_alter_coordinator_options_coordinator_is_chief"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundprogram",
            name="short_description",
            field=models.CharField(
                help_text="Введите название кнопки в боте для данной программы",
                max_length=20,
                verbose_name="Текст на кнопке",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("Юридическая помощь", "Юридическая помощь"),
                    ("Социальная помощь", "Социальная помощь"),
                    ("Психологическая помощь", "Психологическая помощь"),
                ],
                default="Юридическая помощь",
                help_text="Выберите тип помощи для вопроса",
                max_length=100,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
