# Generated by Django 4.2.4 on 2023-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_alter_coordinator_email_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundprogram",
            name="short_description",
            field=models.CharField(
                help_text="Введите название кнопки в боте для данной программы",
                max_length=20,
                verbose_name="Текст на кнопке",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("LEGAL_ASSISTANCE", "Юридическая помощь"),
                    ("SOCIAL_ASSISTANCE", "Социальная помощь"),
                    ("PSYCHOLOGICAL_ASSISTANCE", "Психологическая помощь"),
                ],
                default="LEGAL_ASSISTANCE",
                help_text="Выберите тип помощи для вопроса",
                max_length=100,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
