# Generated by Django 4.2.4 on 2023-09-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations for bot."""

    dependencies = [
        ("bot", "0006_alter_fundprogram_short_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="short_description",
            field=models.CharField(
                help_text="Введите название кнопки в боте для данного вопроса",
                max_length=20,
                verbose_name="Текст на кнопке",
            ),
        ),
    ]
