# Generated by Django 4.2.4 on 2023-08-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    """fasfasf."""

    dependencies = [
        ("core", "0003_alter_region_options"),
        ("bot", "0007_alter_coordinator_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyRegion",
            fields=[],
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.region",),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("LEGAL_ASSISTANCE", "Юридическая помощь"),
                    ("SOCIAL_ASSISTANCE", "Социальная помощь"),
                    ("PSYCHOLOGICAL_ASSISTANCE", "Психологическая помощь"),
                    ("COMMON_QUESTION", "Общий вопрос"),
                ],
                default="LEGAL_ASSISTANCE",
                max_length=100,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
