# Generated by Django 4.2.4 on 2023-08-31 02:41

from django.db import migrations


class Migration(migrations.Migration):
    """Migrations for users."""

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="region",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
