# Generated by Django 4.2.3 on 2023-07-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration for bot_settings app."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Ключ настройки",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название настройки"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255, verbose_name="Значение настройки"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("url", "URL"), ("text", "TEXT")],
                        max_length=100,
                        verbose_name="Тип значения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка бота",
                "verbose_name_plural": "Настройки бота",
                "ordering": ("title",),
            },
        ),
    ]
