# Generated by Django 4.2.3 on 2023-07-21 08:19
from django.db import migrations

from bot_settings.models import BotSettings as BotSettingsModel


def create_donation_url_setting(apps, schema_editor):
    """Create donation_url setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    BotSettings.objects.create(
        key="donation_url",
        title="Ссылка на страницу пожертвований",
        type=BotSettingsModel.URL,
        value="https://detskyfond.info/pomogi/",
    )


def remove_donation_url_setting(apps, schema_editor):
    """Remove donation_url setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    setting = BotSettings.objects.get(key="donation_url")
    setting.delete()


def create_start_message_setting(apps, schema_editor):
    """Create start_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    BotSettings.objects.create(
        key="start_message",
        title="Сообщение при нажатии на кнопку Start",
        type=BotSettingsModel.TEXT,
        value='Здравствуйте! Это бот фонда "Расправь крылья".',
    )


def remove_start_message_setting(apps, schema_editor):
    """Remove start_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    setting = BotSettings.objects.get(key="start_message")
    setting.delete()


def create_help_message_setting(apps, schema_editor):
    """Create help_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    BotSettings.objects.create(
        key="help_message",
        title="Сообщение при нажатии на кнопку Help",
        type=BotSettingsModel.TEXT,
        value="Здесь выводится краткое описание возможностей бота (/help)",
    )


def remove_help_message_setting(apps, schema_editor):
    """Remove help_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    setting = BotSettings.objects.get(key="help_message")
    setting.delete()


def create_assistance_message_setting(apps, schema_editor):
    """Create assistance_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    BotSettings.objects.create(
        key="assistance_message",
        title="Сообщение при нажатии на кнопку Assistance",
        type=BotSettingsModel.TEXT,
        value='Сообщение после нажатия на кнопку "Получить помощь"'
        "(Выбор региона)",
    )


def remove_assistance_message_setting(apps, schema_editor):
    """Remove assistance_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    setting = BotSettings.objects.get(key="assistance_message")
    setting.delete()


class Migration(migrations.Migration):
    """Initial migration for bot_settings app."""

    dependencies = [
        ("bot_settings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_donation_url_setting,
            reverse_code=remove_donation_url_setting,
        ),
        migrations.RunPython(
            create_start_message_setting,
            reverse_code=remove_start_message_setting,
        ),
        migrations.RunPython(
            create_help_message_setting,
            reverse_code=remove_help_message_setting,
        ),
        migrations.RunPython(
            create_assistance_message_setting,
            reverse_code=remove_assistance_message_setting,
        ),
    ]
