# Generated by Django 4.2.3 on 2023-07-21 08:19
from django.db import migrations

from bot_settings.models import BotSettings as BotSettingsModel


def create_donation_url_setting(apps, schema_editor):
    """Create donation_url setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    BotSettings.objects.create(
        key="donation_url",
        title="Ссылка на страницу пожертвований",
        type=BotSettingsModel.URL,
        value="https://detskyfond.info/pomogi/",
    )


def remove_donation_url_setting(apps, schema_editor):
    """Remove donation_url setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    setting = BotSettings.objects.get(key="donation_url")
    setting.delete()


class Migration(migrations.Migration):
    """Initial migration for bot_settings app."""

    dependencies = [
        ("bot_settings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_donation_url_setting,
            reverse_code=remove_donation_url_setting,
        ),
    ]
