# Generated by Django 4.2.4 on 2023-09-01 16:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations for bot settings."""

    dependencies = [
        ("bot_settings", "0002_add_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botsettings",
            name="title",
            field=models.CharField(
                help_text="Введите название настройки для бота",
                max_length=255,
                verbose_name="Название настройки",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="type",
            field=models.CharField(
                choices=[
                    ("url", "Ссылка"),
                    ("text", "Текст"),
                    ("int", "Число"),
                ],
                max_length=100,
                verbose_name="Тип значения",
            ),
        ),
        migrations.AlterField(
            model_name="botsettings",
            name="value",
            field=ckeditor.fields.RichTextField(
                help_text="Введите значение настройки для бота",
                max_length=255,
                verbose_name="Значение настройки",
            ),
        ),
    ]
