# Generated by Django 4.2.4 on 2023-08-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations for bot settings."""

    dependencies = [
        ("bot_settings", "0002_add_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botsettings",
            name="type",
            field=models.CharField(
                choices=[("url", "URL"), ("text", "TEXT"), ("int", "INT")],
                max_length=100,
                verbose_name="Тип значения",
            ),
        ),
    ]
