# Generated by Django 4.2.3 on 2023-07-21 08:19
from django.db import migrations

from bot_settings.models import BotSettings as BotSettingsModel


def create_start_message_setting(apps, schema_editor):
    """Create start_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    BotSettings.objects.create(
        key="start_message",
        title="Сообщение при нажатии на кнопку Start",
        type=BotSettingsModel.TEXT,
        value='Здравствуйте! Это бот фонда "Расправь крылья".',
    )


def remove_start_message_setting(apps, schema_editor):
    """Remove start_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    setting = BotSettings.objects.get(key="start_message")
    setting.delete()


class Migration(migrations.Migration):
    """Initial migration for bot_settings app."""

    dependencies = [
        ("bot_settings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_start_message_setting,
            reverse_code=remove_start_message_setting,
        ),
    ]
