# Generated by Django 4.2.4 on 2023-08-30 11:08

from django.db import migrations


class Migration(migrations.Migration):
    """Migrations for bot settings."""

    dependencies = [
        (
            "bot_settings",
            "0003_alter_botsettings_title_alter_botsettings_value",
        ),
        ("bot_settings", "0003_alter_botsettings_type"),
    ]

    operations = []
