# Generated by Django 4.2.4 on 2023-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bot_settings",
            "0003_alter_botsettings_title_alter_botsettings_value",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="botsettings",
            name="type",
            field=models.CharField(
                choices=[("url", "Ссылка"), ("text", "Текст")],
                max_length=100,
                verbose_name="Тип значения",
            ),
        ),
    ]
