# Generated by Django 4.2.3 on 2023-07-21 08:19
from django.db import migrations

from bot_settings.models import BotSettings as BotSettingsModel


def create_assistance_message_setting(apps, schema_editor):
    """Create assistance_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    BotSettings.objects.create(
        key="assistance_message",
        title="Сообщение при нажатии на кнопку Assistance",
        type=BotSettingsModel.TEXT,
        value='Сообщение после нажатия на кнопку "Получить помощь"'
        "(Выбор региона)",
    )


def remove_assistance_message_setting(apps, schema_editor):
    """Remove assistance_message setting instance."""
    BotSettings = apps.get_model("bot_settings", "BotSettings")
    setting = BotSettings.objects.get(key="assistance_message")
    setting.delete()


class Migration(migrations.Migration):
    """Initial migration for bot_settings app."""

    dependencies = [
        ("bot_settings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_assistance_message_setting,
            reverse_code=remove_assistance_message_setting,
        ),
    ]
