# Generated by Django 4.2.4 on 2023-09-01 01:36

from django.db import migrations


class Migration(migrations.Migration):
    """Migrations for bot settings."""

    dependencies = [
        ("bot_settings", "0004_alter_botsettings_type"),
        ("bot_settings", "0004_merge_20230830_1608"),
    ]

    operations = []
