# Generated by Django 4.2.4 on 2023-08-15 19:23

from django.db import migrations


class Migration(migrations.Migration):
    """Initial migration for bot_settings app."""

    dependencies = [
        ("bot_settings", "0004_add_help_message"),
        ("bot_settings", "0005_add_assistance_message"),
        (
            "bot_settings",
            "0006_merge_0002_add_donation_url_0003_add_start_message",
        ),
    ]

    operations = []
