# Generated by Django 4.2.3 on 2023-08-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("region_name", models.CharField(max_length=200, unique=True)),
                ("region_key", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
                "ordering": ("region_name",),
            },
        ),
    ]
