# Generated by Django 4.2.4 on 2023-09-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations for bot."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region_name",
                    models.CharField(
                        help_text="Это название так же будет отображаться на кнопках бота",
                        max_length=200,
                        unique=True,
                        verbose_name="Название региона",
                    ),
                ),
                ("region_key", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
                "ordering": ("region_name",),
            },
        ),
    ]
