# Generated by Django 4.2.3 on 2023-07-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="region_key",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
