# Generated by Django 4.2.4 on 2023-08-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations for bot."""

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="region_name",
            field=models.CharField(
                help_text="Это название также будет отображаться на кнопках бота",
                max_length=200,
                unique=True,
                verbose_name="Название региона",
            ),
        ),
    ]
