# Generated by Django 4.2.3 on 2023-08-02 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_region_region_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "ordering": ("region_name",),
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
            },
        ),
    ]
