version: '3.8'

services:
  bot:
    image: "ghcr.io/studio-yandex-practicum/spread_wings_bot:develop"
    #restart: always
    env_file:
      - ../../src/.env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    command: bash -c "
        mkdir /data/log -p
        && mkdir /data/bases -p
        && touch /data/log/redis-server.log
        && redis-server /usr/local/etc/redis.conf
      "

    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
      - data_value:/data

volumes:
  data_value:
