version: '3.8'
name: spread-wings-stage

services:

  redis:
    image: redis:latest
    container_name: spread-wings-redis
    ports:
      - "6379:6379"
    restart: always
    command: > 
      bash -c "
        mkdir /data/log -p &&
        mkdir /data/bases -p &&
        touch /data/log/redis-server.log &&
        redis-server /usr/local/etc/redis.conf | tee -a /data/log/redis-server.log
      "
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
      - data_value:/data
    networks:
      - spread-wings-network

  db:
    image: postgres:15.3-alpine
    container_name: spread-wings-db
    env_file:
      - ./.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - spread-wings-network

#    find out how to implement properly. Currently does not work, error occures
#    "You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path"
#    command: >
#      bash -c "
#        python manage.py migrate &&
#        python manage.py collectstatic --noinput &&
#        python manage.py createsuperuser --email example@yandex.ru --noinput
#      "

  bot:
    image: "ghcr.io/studio-yandex-practicum/spread_wings_bot:develop"
    container_name: spread-wings-bot
    depends_on:
      - redis
      - db
    restart: always
    env_file:
      - ./.env
    networks:
      - spread-wings-network

  nginx:
    image: nginx:1.21.3-alpine
    container_name: spread-wings-nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx.stage.conf:/etc/nginx/conf.d/default.conf
      - ../../src/static:/var/html/static/
      - ../../src/media:/var/html/media/
    depends_on:
      - bot
    restart: always
    networks:
      - spread-wings-network

volumes:
  data_value:
  db_data:
  static:
  media:

networks:
  spread-wings-network:
