version: '3.9'

services:
  db:
    image: postgres:15.3-alpine
    container_name: spread-wings-db
    env_file:
      - ../../.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
