version: '3.8'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    command: bash -c " mkdir /data/log -p && mkdir /data/bases -p && touch /data/log/redis-server.log && redis-server /usr/local/etc/redis.conf "
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
      - data_value:/data

  db:
    image: postgres:15.3-alpine
    container_name: spread-wings-db
    env_file:
      - ./.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  bot:
    image: "ghcr.io/studio-yandex-practicum/spread_wings_bot:develop"
    depends_on:
      - redis
      - db
    restart: always
    env_file:
      - ./.env
    command: >
      bash -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        python manage.py createsuperuser --email example@yandex.ru --noinput &&
        poetry run uvicorn config.asgi:application --reload
      "

volumes:
  data_value:
  db_data:
