name: Python safety check

on:
  pull_request:
    branches:
      - develop
      - master

env:
  DEVELOP: requirements/develop.txt
  PRODUCTION: requirements/production.txt
  # https://github.com/aufdenpunkt/python-safety-check#env-variables
  DEP_PATH: None

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v3

      - name: Requiremets path to production branch
        if: ${{ github.base_ref == 'master' }}
        run: echo "DEP_PATH=$PRODUCTION" >> $GITHUB_ENV

      - name: Requiremets path to develop branch
        if: ${{ github.base_ref == 'develop' }}
        run: echo "DEP_PATH=$DEVELOP" >> $GITHUB_ENV

      - name: Run migrations check
        run: |
          cd src/
          python manage.py makemigrations --check --dry-run
