name: App test workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r ../rerequirements/develop.txt

    - name: Isort
      run:
        poetry run isort

    - name: Test with flake8
      run: poetry run flake8

    - name: Test with pytest
      run: poetry run pytest
